### ISSUE TITLE
Entrevistas a expertos

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#11]
### Descripción

Durante esta etapa del proyecto necesitamos entrevistar a los principales expertos que conocen del tema o proceso que estamos tratando de mejorar para conocer los diferentes puntos de vista de los direferentes actores.

Script de entrevistas:
- Introducir el sprint
- Revision de los pizarrones
- Abrir la puerta a que platiquen todo lo que saben
- Preguntar todo lo que se pueda

### Listado de tareas

- [x] Conseguir a los expertos
- [x] Tener tiempo limitado para cada
- [x] Tomar notas individualmente

### Definition of Done

- [x] ¿Se entrevistaron a todos los expertos?

**Comment by Doigo12** [comment]
Se lograron las entrevistas de manera sobresaliente.
