### ISSUE TITLE
Definir problema principal

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#13]
### Descripción

Escoger cual es el problema principal del proyecto, dentro del mapa cual es el punto central o mas importante, igualmente dentro de las preguntas del sprint cual es la principal a resonder.

### Listado de tareas

- [x] Identificar parte principal dentro del mapa
- [x] Identificar pregunta principal de las preguntas del sprint

### Definition of Done

- [x] ¿Se tiene una definicion real?

**Comment by Doigo12** [comment]
Se encontró la definición del problema principal.
