### ISSUE TITLE
Investigacion de mercado

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#14]
### Descripción

Durante el intern entre el dia uno del sprint de diseño y el dia dos se tendra una tarea de buscar por ejemplos de sistemas que puedan aplicar para lo que estamos buscando resolver, pueden ser competidores, puede ser algo totalmente fuera del sector pero que pueda aplicarse algo al sistema.

### Listado de tareas

- [x] Buscar sistemas que puedan tener componentes que puedan aplicar a nuestro diseño

### Definition of Done

- [x] ¿Se tienen suficientes ejemplo?

**Comment by Doigo12** [comment]
Se realizó la busqueda.
