### ISSUE TITLE
Desmostracion de investigacion de mercado

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#16]
### Descripción

Cada persona del equipo de trabajo va a presentar dos de los ejemplos que encontro, se tienen solo 3 minutos para demostrar que es lo que les gusto y porque.

### Listado de tareas

- [x] Buscar los dos sistemas a presentar
- [x] Presentar

### Definition of Done

- [x] ¿Todos presentaron 2 propuestas?

**Comment by Doigo12** [comment]
Se realizaron las propuestas de manera satisfactoria por parte de todos los integrantes del equipo.
