### ISSUE TITLE
Capturar ideas de los demos

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#18]
### Descripción

Paralelo a las demos, una persona tiene que estar haciendo sketch de las partes que fueron buenas y gustaron a los demas en post-its para capturar las ideas

### Listado de tareas

- [x] Capturar ideas
- [x] Pegar las ideas en la pared

### Definition of Done

- [x] ¿Se capturaron todas las ideas?

**Comment by Doigo12** [comment]
Se realizó el registro de todas las ideas.
