### ISSUE TITLE
Sketch de 4 pasos

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#21]
### Descripción

Este proceso tiene 4 partes

1. Notas 
- Tomar notas acerca de todo lo que se tiene en los pizarrones en el cuarto
2. Ideas
- Cada persona organiza sus ideas de como vio todo lo de las notas y aterriza mas sus ideas
3. Crazy 8s
- Durante minutos se haran sketchs cada 30s de una buena idea que tengan, pueden iterar sobre estas ideas o dibujar ideas nuevas 
4. Solution sketch
- Cada persona tendra el tiempo para un tiempo para hacer un dibujo de la mejor solucion que encuentren.

### Listado de tareas

- [x] Nota
- [x] Ideas
- [x] Crazy 8s
- [x] Solution sketch

### Definition of Done

- [x] ¿Se hicieron todas las etapas del proceso?

**Comment by Doigo12** [comment]
Se realizaron todas las etapas del proceso.
