### ISSUE TITLE
Heat map soluciones

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#28]
### Descripción

Las soluciones de cada integrante del equipo se pegaran en la pared/pizarron y a cada integrante del equipo se le danran stickers circulares para votar por las mejores soluciones o las mejores ideas individuales, si se tienen dudas se deben poner en post-its

### Listado de tareas

- [x] Suficientes stickers para todos
- [x] Votar por las soluciones

### Definition of Done

- [x] ¿Todos ya votaron por sus mejores soluciones?

**Comment by Doigo12** [comment]
Se realizó la votacion de las diferentes soluciones, ademas del super voto del product owner.
