### ISSUE TITLE
Narrar soluciones y puntos clave

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#31]
### Descripción

Durante esta parte del proyecto una persona tiene que empezar a narrar para dibujo en base a lo que ve y las partes que tienen mas votaciones, al final de lo que se diga el que lo dibujo explica las partes que faltaron de explicarse.

### Listado de tareas

- [x] Explicar cada dibujo
- [x] Tomar notas de las explicaciones
- [x] Resaltar lo importante cada quien de su dibujo

### Definition of Done

- [x] ¿Se narraron ya todas las soluciones?
- [x] ¿Se vieron ya todas las partes importantes?

**Comment by Doigo12** [comment]
Todas las soluciones presentadas fueron narradas, ademas de las partes importantes.
