### ISSUE TITLE
Votacion de soluciones

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#34]
### Descripción

Despues de las explicaciones cada uno tiene un voto para darle a lo que mas les gusto, puede ser un componente o puede ser un dibujo completo.

### Listado de tareas

- [x] Todos tienen un voto
- [x] El product owner tiene 3 votos
- [x] Votar

### Definition of Done

- [x] ¿Ya votaron todos?

**Comment by Doigo12** [comment]
Se tuvo una votacion de soluciones exitosa.
