### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#35]
### Descripción

Una vez que se tiene la mejor idea y mejores partes de todos los dibujos se puede empezar a hacer un storyboard del proceso que se tendra de con el prototipo terminado.

### Listado de tareas

- [x] Hacer un recuadro en el pizarron para hacer el storyboard
- [x] Hacer la historia del proceso que se tendra

### Definition of Done

- [x] ¿Se tiene un storyboard real, completo y realista?

**Comment by Doigo12** [comment]
Se completó el storyboard de manera exitosa, imagenes del storyboard se encuentran dentro de la carpeta de equipo.
