### ISSUE TITLE
Definir formato de las entrevistas con los usuarios

### ISSUE THREAD

**Issue by esthephanyayala** [ProyectoIntegrador2018/blue-lab#36]
### Descripción
Se realizara una plantilla de preguntas para la entrevista que tendra como tema principal el prototipo del producto.
### Listado de tareas

- [x] Realizacion de preguntas
- [x] Escoger las preguntas mas importantes 

### Definition of Done

- [x] ¿Las preguntas abarcan la funcionalidad que se desea verificar?

**Comment by Doigo12** [comment]
Se tienen listas las preguntas y se agregaron como caso de prueba en el documento de pruebas.
