### ISSUE TITLE
Creacion de prototipo para entrevistas

### ISSUE THREAD

**Issue by esthephanyayala** [ProyectoIntegrador2018/blue-lab#37]
### Descripción
Realización de un prototipo no funcional que sera utilizado en la actividad de se realizacion de entrevistas a usuarios presenciales 

### Listado de tareas

- [x] Diseñar cada pantalla
- [x] Conectar pantallas para seguir el workflow 

### Definition of Done

- [x] ¿El prototipo abarca todas las funcionalidades que se quieren probar ?

**Comment by Doigo12** [comment]
Se elaboró el prototipo exitosamente.
