### ISSUE TITLE
Entrevistas con usuarios potenciales con prototipo

### ISSUE THREAD

**Issue by esthephanyayala** [ProyectoIntegrador2018/blue-lab#38]
### Descripción
Se realizara entrevista con usuarios potenciales a cerca de nuestro prototipo con la finalidad de aceptar o rechazar la hipotesis del prototipo inicial. 

### Listado de tareas

- [x] Realización de entrevista
- [x] Tomar notas de los pasos que seguia el usuario con el prototipo
- [x] Escribir reflexiones finales de la entrevista a cada usuario

### Definition of Done

- [x] ¿El usuario encontro la funcionalidad que se le pidió al inicio de la entrevista?

**Comment by Doigo12** [comment]
Las pruebas se realizaron exitosamente, los resultados se encuentran explicados en la documentacion de pruebas.
