### ISSUE TITLE
Rediseño de prototipo en base a entrevistas

### ISSUE THREAD

**Issue by esthephanyayala** [ProyectoIntegrador2018/blue-lab#39]
### Descripción
En base a las entrevistas con clientes potenciales, se ajustara el prototipo inicial para mejorar el producto final.

### Listado de tareas

- [x] Leer las conclusiones de las entrevistas
- [x] Identificar areas de oportunidad dentro del prototipo
- [x] Realización de mejoras

### Definition of Done

- [x] ¿Se mejoraron las areas de oportunidad del prototipo inicial?

**Comment by Doigo12** [comment]
Se realizó exitosamente el rediseño del prototipo, imagenes del mismo se encuentran en documento.
