### ISSUE TITLE
Identificar usuarios potenciales 

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#5]
### Descripción

Se deberen encontrar 5 usuarios que cumplan con la descripcion de lo que puede ser un nuevo cliente para BluePeople

### Listado de tareas

- [x] Encontrar usuario 1
- [x] Encontrar usuario 2
- [x] Encontrar usuario 3
- [x] Encontrar usuario 4
- [x] Encontrar usuario 5

### Definition of Done

- [x] ¿Los 5 usuarios cumplen con el perfil de un nuevo cliente de BluePeople?

**Comment by Doigo12** [comment]
Se entrevistaron exitosamente a todos los usuarios de prueba.
